### ISSUE TITLE
Cuthill-Mckeeを追加する

### ISSUE THREAD

**Issue by LWisteria** [fixstars/AlgebraicBlockMulticolorOrdering#1]
Cuthill-Mckeeによる実装を追加してください

**Comment by LWisteria** [comment]
@kurenaif 担当お願いします。とりあえずは動かしてみてください。

**Comment by kurenaif** [comment]
動かすために必要そうなこと

- [x] リポジトリのクローン(二段階認証のため鍵生成等が必要)
- [x] VisualStudioでソリューションファイルを開けることの確認(.slnファイルの更新 これはcommitに含める…?)
- [ ] boostのインストール
- [ ] Build確認

**Comment by LWisteria** [comment]
> .slnファイルの更新 これはcommitに含める…?

はい、入れちゃってください（これだけで1コミットにしておいてもらえれば

**Comment by kurenaif** [comment]
Cuthill-Mckee法の実装についてはこちらの23ページ目以降を参考にします。 https://www.cc.u-tokyo.ac.jp/support/kosyu/18/omp-02.pdf まずは並列化を気にせずに、幅優先的にレベルを割り当てる手法を実装し、その後隣接ノードの排除を実装して並列化に備えます

**Comment by kurenaif** [comment]
### 隣接ノードを無視しないcuthill-mckee法(並列化できません) の実装方針

1. 次数が最も少ないノードを探す: index_1のoffsetのdiffを見ていけば隣接行列の次数がわかる(対角行列を含むと自分自身を含むので注意！)
2. 次数が最も少ないノードから幅優先探索をする: queue回すだけ(自明にlevelが小さい順に割り当てられるので、priority_queueでなくてもOK)
note: levelはBlockにならい、0をINVALID_LEVELに設定, 1以上であれば割り当て済み
TODO: あとで隣接ノードを無視するように実装する
3. CreateRowで並び替え
4. GaussSeidel, SymmetryGaussSeidel

**Comment by kurenaif** [comment]
簡単に幅優先探索を実行してみた結果、非連結グラフを探索しうることがわかりました。
連結してないグラフ同士は独立のはずなので、並列計算できるはずです。
CM法を解説している記事をいくつか読んでも非連結グラフの取り扱いについては書いていませんでした。
現状これを考慮せず、もしグラフを幅優先で探索していき、行き先を見失ったら再び最小次数のノードを探して最大level+1をつけて再探索する方針で実装します。

**Comment by kurenaif** [comment]
#### 3. CreateRowでの並べ替えでの注意点

レベルでソートした後、グラフの次数順でもソートする

**Comment by kurenaif** [comment]
### 同じレベル内での隣接ノードを排除したラベリング方法

現状幅優先探索の条件を以下のようにしている
```
もし、未割当であればレベルを割り当てる
```
setを一つ用意して、以下のように改良する
```
もし、未割当で かつ set内にノードが存在しなければ、
レベルを割り当てる
```

**Comment by kurenaif** [comment]
`CreateRowForCuthillMckee` を関数にするかどうか以外の部分のレビュー対応終わりました。
再度レビューよろしくお願いします。

**Comment by kurenaif** [comment]
`CreateRowForCuthillMckee` を展開して、追加レビュー内容を修正しました。
確認よろしくおねがいします。

**Comment by kurenaif** [comment]
[こちら](https://github.com/fixstars/AlgebraicBlockMulticolorOrdering/pull/10)で隣接点を考慮しない版の実装は完了しました。
これから隣接点を考慮する版を実装します。

**Comment by kurenaif** [comment]
pull リクエストで議論があったとおり、既存のCuthill-Mckee関数に上書きする形で実装します

**Comment by kurenaif** [comment]
### 同じレベル内での隣接点を排除したラベリング方法

高々Indexは `N` 個で連番なので、setを使わなくても良さそう

| 項目 | set | 配列 |
|:-----------:|:------------:|:------------:|
| メモリ空間 | 隣接点のみ | O(N) |
| 点の追加 | O(logN) | O(1) |
| 点の検索 | O(logN) | O(1) |

行列確保してる時点でO(N^2)持ってるし、O(N)くらいはあっても良さそう?

**Comment by kurenaif** [comment]
配列を用いて隣接点をメモする方法だとN回N個の要素を持つ配列を用意しなければならないためよくない気がする 一度setで実装します。

**Comment by kurenaif** [comment]
メモをリセットする回数はレベルと同じ数でしたね

**Comment by kurenaif** [comment]
同じレベル内での隣接点を排除するCM法を実装しました。レビューよろしくおねがいします。
https://github.com/fixstars/AlgebraicBlockMulticolorOrdering/pull/11

**Comment by LWisteria** [comment]
@kurenaif 
実装は終わったと思いますが、[doc](https://github.com/fixstars/AlgebraicBlockMulticolorOrdering/tree/master/doc)にある2つのスプレッドシートで、行列の形や収束の様子を見せているところがあるので、最後にそちらを更新してもらえますか？
（それが終わったらチケット完了と思います）

**Comment by kurenaif** [comment]
https://github.com/fixstars/AlgebraicBlockMulticolorOrdering/pull/12
cuthill-mckee法の計算結果をREADME.mdに追加しました

**Comment by kurenaif** [comment]
レビューよろしくおねがいします

**Comment by kurenaif** [comment]
@LWisteria docのレビュー対応終わりました。
https://github.com/fixstars/AlgebraicBlockMulticolorOrdering/pull/12
レビューよろしくおねがいします！

**Comment by LWisteria** [comment]
全部完了ですね。おつかれさまでした！
