### ISSUE TITLE
リポジトリをvisualstudio2017仕様に対応させる

### ISSUE THREAD

**Issue by kurenaif** [fixstars/AlgebraicBlockMulticolorOrdering#2]

**Comment by kurenaif** [comment]
動かすために必要そうなこと

- [ ] リポジトリのクローン(二段階認証のため鍵生成等が必要)
- [ ] VisualStudioでソリューションファイルを開けることの確認(.slnファイルの更新 これはcommitに含める…?)
- [ ] boostのインストール(NuGetで対応 https://www.nuget.org/packages/boost-vc141/)
- [ ] Build確認(VisualStudio上でコンパイル&実行に成功)

**Comment by LWisteria** [comment]
これ #3 で終わったので閉じますね。
