### ISSUE TITLE
AlgebraicBlockMultiColoringのblockのINVALID_BLOCKに関して

### ISSUE THREAD

**Issue by kurenaif** [fixstars/AlgebraicBlockMulticolorOrdering#6]
AlgebraicBlockMultiColoringの冒頭に
```
constexpr auto INVALID_BLOCK = Block(0);
auto block = std::make_unique<Block[]>(N);

constexpr auto MAX_COUNT_PER_BLOCK = BLOCK_SIZE*BLOCK_SIZE; // 1ブロック内の要素数
constexpr auto MAX_BLOCK_COUNT = N; // 最大は、1ブロック1要素の時
auto countPerBlock = std::make_unique<std::size_t[]>(MAX_BLOCK_COUNT);
```
と書いていて、blockはINVAILD_BLOCKで初期化されてあるものとして取り扱っていますが、
こちらはlevelとは違いfillはしなくて問題ないでしょうか？

**Comment by LWisteria** [comment]
確認します。

次回からでいいので、コードを指摘する時はそこへのリンクを貼ってくれると助かります・・・

**Comment by LWisteria** [comment]
あぁ、確かに[まずい](https://github.com/fixstars/AlgebraicBlockMulticolorOrdering/blob/9daa026d3460af42f484fefbfa169e333a2ed567/Abmc/Abmc.hpp#L324-L337)ですね。直します。

**Comment by LWisteria** [comment]
#7 で直したので閉じます。指摘ありがとうございました。
