### ISSUE TITLE
AlgebraicBlockMultiColoringのcandidateのforの初期化に関して

### ISSUE THREAD

**Issue by kurenaif** [fixstars/AlgebraicBlockMulticolorOrdering#8]
[AlgebraicBlockMultiColoringの探索する際のforの初期化部分](https://github.com/fixstars/AlgebraicBlockMulticolorOrdering/blob/a71d3fcc187cb4541b439cde14f4e79aecb37eca/Abmc/Abmc.hpp#L366) に関して

候補点がない場合に、このループに突入すると、`candidate.empty() == true` の状態にもかかわらず `candidate.front()` が呼ばれるためエラー落ちします

確認よろしくおねがいします。

**Comment by kurenaif** [comment]
cuthill-Mckeeの幅優先探索の時と同様に、
forの初期化はなくてもいいと思います。

**Comment by LWisteria** [comment]
#9 で直しました。指摘ありがとうございました。
